healthcare_professionals = [
    'allergist (coming soon)',
    'anesthesiologist (coming soon)',
    'audiologist (coming soon)',
    'cardiologist (coming soon)',
    'chiropractor (coming soon)',
    'dentist (coming soon)',
    'dermatologist (coming soon)',
    'dietitian',
    'emergency medicine physician (coming soon)',
    'endocrinologist (coming soon)',
    'epidemiologist (coming soon)',
    'family medicine physician (coming soon)',
    'gastroenterologist (coming soon)',
    'genetic counselor (coming soon)',
    'geriatrician (coming soon)',
    'gynecologist (coming soon)',
    'hematologist (coming soon)',
    'infectious disease specialist (coming soon)',
    'internist (coming soon)',
    'medical geneticist (coming soon)',
    'microbiologist (coming soon)',
    'midwife (coming soon)',
    'neonatologist (coming soon)',
    'nephrologist (coming soon)',
    'neurologist (coming soon)',
    'neurosurgeon (coming soon)',
    'nurse (coming soon)',
    'nurse practitioner (coming soon)',
    'nutritionist (coming soon)',
    'obstetrician (coming soon)',
    'occupational therapist (coming soon)',
    'oncologist (coming soon)',
    'ophthalmologist (coming soon)',
    'optometrist (coming soon)',
    'orthodontist (coming soon)',
    'orthopedic surgeon (coming soon)',
    'otolaryngologist (coming soon)',
    'pathologist (coming soon)',
    'pediatrician (coming soon)',
    'pharmacist (coming soon)',
    'physical therapist (coming soon)',
    'physician assistant (coming soon)',
    'plastic surgeon (coming soon)',
    'podiatrist (coming soon)',
    'psychiatrist (coming soon)',
    'psychologist (coming soon)',
    'pulmonologist (coming soon)',
    'radiologist (coming soon)',
    'registered nurse (coming soon)',
    'rheumatologist (coming soon)',
    'surgeon (coming soon)',
    'urologist (coming soon)',
    'veterinarian (coming soon)',
    'fitness coach'
]

collab_pages = {
    "dietitian": "Dietitian",
    "fitness coach": "Fitness Coach"
}

health_conditions = [
    'diabetes type 1',
    'diabetes type 2 (coming soon)',
    'obesity (coming soon)',
    'hypertension (coming soon)',
    'heart disease (coming soon)',
    'high cholesterol (coming soon)',
    'osteoporosis (coming soon)',
    'polycystic ovary syndrome (coming soon)',
    'eating disorders (coming soon)',
    'arthritis (coming soon)',
    'digestive disorders (coming soon)',
    'cancer recovery (coming soon)',
    'muscle wasting diseases (coming soon)',
    'metabolic syndrome (coming soon)',
    'chronic kidney disease (coming soon)',
    'asthma (coming soon)',
    'stroke recovery (coming soon)',
    'traumatic brain injury (coming soon)',
    'spinal cord injury (coming soon)',
    'chronic pain (coming soon)',
    'autoimmune disorders (coming soon)',
    'chronic obstructive pulmonary disease (coming soon)',
    'dementia and cognitive disorders (coming soon)',
    'mood disorders (coming soon)',
    'anxiety disorders (coming soon)',
    'thyroid disorders (coming soon)',
    'skin conditions like psoriasis and eczema (coming soon)',
    'eye conditions like glaucoma and macular degeneration (coming soon)',
    'hearing loss and tinnitus (coming soon)',
    'infectious diseases like tuberculosis and HIV/AIDS (coming soon)',
    'liver diseases (coming soon)',
    'sleep disorders (coming soon)',
    'wound care and ulcer management (coming soon)',
    'bone fractures and joint replacements (coming soon)',
    'rare genetic disorders (coming soon)'
]

